version: "3.8"
services:
  front:
    build: ./
    container_name: node
    volumes:
      - ./front:/front
    ports:
      - 3000:3000
    command: npm run start
    tty: true 
    stdin_open: true